[advisories]
vulnerability = "deny"
unmaintained = "allow"
notice = "allow"
unsound = "deny"
severity-threshold = "medium"
ignore = [
    # No fix available, but only applies to Windows, hence not a problem for us.
    "RUSTSEC-2021-0145",
]


[bans]
deny = [
    # NOTE: `boring`, `ring` or `rustls` crates should be used instead
    { name = "openssl" },
    { name = "openssl-sys" },
]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "allow"
allow-git = []

[licenses]
unlicensed = "allow"
allow-osi-fsf-free = "either"
copyleft = "deny"
allow = ["MPL-2.0"]
confidence-threshold = 0.9
